(function(){"use strict";var D=window.DSPDF;var state={base:null,insert:null,baseBuffer:null,insertBuffer:null,pdf:null,previewToken:0,done:false};function el(id){return document.getElementById(id)}
function resetOutput(){
  state.previewToken++;
  state.done=false;
  el('insert-progress').hidden=true;
  el('insert-progress').querySelector('p').textContent='Preparing your PDF…';
  el('insert-alert').hidden=true;
  el('insert-alert').textContent='';
  el('insert-status').textContent='';
  el('insert-panel').hidden=true;
  el('insert-preview').hidden=true;
  el('insert-preview-strip').innerHTML='';
  el('insert-position').innerHTML='';
}
function loadPdfJs(){if(window.pdfjsLib){window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';return Promise.resolve()}return new Promise(function(res,rej){var s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=function(){window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';res()};s.onerror=function(){rej(new Error('PDF preview library could not be loaded.'))};document.head.appendChild(s)})}
function selectPosition(i){el('insert-position').value=String(i);updateSelection()}
function updateSelection(){var v=Number(el('insert-position').value||0);document.querySelectorAll('#insert-preview-strip [data-before]').forEach(function(n){var yes=Number(n.dataset.before)===v;n.classList.toggle('is-insert-target',yes);var b=n.querySelector('.insert-badge');if(b)b.hidden=!yes});var a=document.querySelector('#insert-preview-strip [data-after-last]');if(a){var yes=v===state.pdf.numPages;a.classList.toggle('is-insert-target',yes);var b=a.querySelector('.insert-badge');if(b)b.hidden=!yes}}
async function renderPreview(){var host=el('insert-preview'),strip=el('insert-preview-strip');host.hidden=false;strip.innerHTML='<p class="text-muted">Rendering page preview…</p>';var token=++state.previewToken;try{var frag=document.createDocumentFragment(),max=Math.min(state.pdf.numPages,20);for(var i=1;i<=max;i++){if(token!==state.previewToken)return;var card=document.createElement('button');card.type='button';card.className='preview-pdf-item';card.dataset.before=String(i-1);card.setAttribute('aria-label','Insert PDF before page '+i);card.innerHTML='<span class="insert-badge blank-insert-badge" hidden>Insert here</span><canvas></canvas><small>Page '+i+'</small>';card.addEventListener('click',(function(n){return function(){selectPosition(n)}})(i-1));frag.appendChild(card);var pg=await state.pdf.getPage(i),vp=pg.getViewport({scale:.5}),c=card.querySelector('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await pg.render({canvasContext:c.getContext('2d'),viewport:vp}).promise}if(state.pdf.numPages>20){var note=document.createElement('p');note.className='text-muted';note.textContent='Preview shows the first 20 pages for performance. Use the position menu for later pages.';frag.appendChild(note)}var after=document.createElement('button');after.type='button';after.className='preview-pdf-item';after.dataset.afterLast='true';after.setAttribute('aria-label','Insert PDF after the last page');after.innerHTML='<span class="insert-badge blank-insert-badge" hidden>Insert here</span><span class="blank-page-placeholder">＋</span><small>After last page</small>';after.addEventListener('click',function(){selectPosition(state.pdf.numPages)});frag.appendChild(after);strip.innerHTML='';strip.appendChild(frag);updateSelection()}catch(e){strip.innerHTML='<p class="text-muted">Preview unavailable. You can still choose the insertion position from the menu.</p>'}}
async function refresh(){if(!state.base||!state.insert)return;el('insert-panel').hidden=false;el('insert-status').textContent=state.base.name+' + '+state.insert.name;var sel=el('insert-position');sel.innerHTML='';for(var i=0;i<=state.pdf.numPages;i++){var o=document.createElement('option');o.value=i;o.textContent=i===state.pdf.numPages?'After last page':'Before page '+(i+1);sel.appendChild(o)}await renderPreview()}
async function loadBase(f){try{resetOutput();D.showInfo('insert-alert','Reading main PDF…');state.base=f;state.baseBuffer=await D.fileToArrayBuffer(f);await loadPdfJs();state.pdf=await window.pdfjsLib.getDocument({data:state.baseBuffer.slice(0)}).promise;D.clearAlert('insert-alert');if(state.insert)refresh()}catch(e){D.showError('insert-alert',D.humanError(e,'Could not open the main PDF.'))}}
async function loadInsert(f){try{resetOutput();D.showInfo('insert-alert','Reading PDF to insert…');state.insert=f;state.insertBuffer=await D.fileToArrayBuffer(f);await D.ensurePdfLib();D.clearAlert('insert-alert');if(state.base)refresh()}catch(e){D.showError('insert-alert',D.humanError(e,'Could not open the PDF to insert.'))}}
async function apply(){el('insert-progress').querySelector('p').textContent='Preparing your PDF…';if(!state.base||!state.insert){D.showError('insert-alert','Choose both PDFs first.');return}el('insert-progress').hidden=false;try{var r=await D.runPdfOperation('insertPdf',{baseBuffer:state.baseBuffer.slice(0),insertBuffer:state.insertBuffer.slice(0),position:Number(el('insert-position').value||0)});var name=(state.base.name||'document.pdf').replace(/\.pdf$/i,'');D.downloadBlob(new Blob([r.bytes],{type:'application/pdf'}),'dsutility-'+name+'-with-inserted-pages.pdf');state.done=true;el('insert-progress').querySelector('p').textContent='Done — '+r.pageCount+' pages in the new PDF.'}catch(e){D.showError('insert-alert',D.humanError(e,'Could not insert the PDF.'))}}
function init(){new D.UploadZone('#uz-base',{accept:'application/pdf,.pdf',onFiles:function(fs){if(fs[0])loadBase(fs[0])}});new D.UploadZone('#uz-insert',{accept:'application/pdf,.pdf',onFiles:function(fs){if(fs[0])loadInsert(fs[0])}});el('insert-position').addEventListener('change',updateSelection);el('insert-apply').addEventListener('click',apply)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()})();