(function(){
"use strict";
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9\u0900-\u097f]+/g,' ')}
function score(item,q){var n=norm(q).trim();if(!n)return 0;var aliases={'ocr':'ocr pdf image to text','da':'da arrear dearness allowance government','gpf':'gpf provident fund government','nps':'nps pension','ups':'unified pension','sip':'systematic investment plan','fd':'fixed deposit','rd':'recurring deposit','swp':'systematic withdrawal plan','photo':'passport photo image','resume':'resume cv','biodata':'marriage biodata','krutidev':'krutidev unicode hindi','unicode':'unicode hindi krutidev','compress':'compress image pdf','watermark':'watermark signature'};var t=norm(item.title+' '+item.desc+' '+item.href+' '+(aliases[n]||''));var words=n.split(/\s+/);var sc=0;words.forEach(function(w){if(!w)return;if(norm(item.title).indexOf(w)>=0)sc+=5;else if(norm(item.desc).indexOf(w)>=0)sc+=2;else if(t.indexOf(w)>=0)sc+=1});return sc}
function getTools(){var source=(location.pathname.indexOf('/tools/')===0?'index.html':'tools/index.html');return fetch(source,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('Tool index unavailable');return r.text()}).then(function(html){var doc=new DOMParser().parseFromString(html,'text/html');return Array.prototype.slice.call(doc.querySelectorAll('.tool-card')).map(function(x){var h=x.querySelector('.tool-card__title'),d=x.querySelector('.tool-card__desc'),raw=x.getAttribute('href')||'';return{title:h?h.textContent.trim():'Tool',desc:d?d.textContent.trim():'',href:new URL(raw,new URL(source,location.href)).href}})}).catch(function(){return[]})}
function home(){var input=document.getElementById('homeToolSearch'),box=document.getElementById('homeSearchResults'),btn=document.getElementById('homeToolSearchBtn');if(!input||!box)return;var toolsPromise=getTools();function render(q){q=q.trim();if(!q){box.hidden=true;input.setAttribute('aria-expanded','false');return}toolsPromise.then(function(tools){var ranked=tools.map(function(x){return{x:x,s:score(x,q)}}).filter(function(x){return x.s>0}).sort(function(a,b){return b.s-a.s||a.x.title.localeCompare(b.x.title)}).slice(0,8);box.innerHTML='';if(!ranked.length){box.innerHTML='<div class="home-search-empty">No matching tool found. Try another word such as <strong>OCR</strong>, <strong>PDF</strong>, <strong>DA</strong> or <strong>image</strong>.</div>'}else{ranked.forEach(function(r){var a=document.createElement('a');a.href=r.x.href;a.className='home-search-result';a.setAttribute('role','option');a.innerHTML='<span class="home-search-result__icon">↗</span><span><strong>'+r.x.title+'</strong><small>'+r.x.desc+'</small></span>';box.appendChild(a)});var all=document.createElement('a');all.className='home-search-result home-search-result--all';all.href='tools/index.html?search='+encodeURIComponent(q);all.innerHTML='<span>⌕</span><strong>View all matching tools</strong>';box.appendChild(all)}box.hidden=false;input.setAttribute('aria-expanded','true')})}
input.addEventListener('input',function(){render(input.value)});input.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();var q=input.value.trim();if(q)location.href='tools/index.html?search='+encodeURIComponent(q)}});btn.addEventListener('click',function(){var q=input.value.trim();if(q)render(q);else location.href='tools/index.html'});document.addEventListener('click',function(e){if(!e.target.closest('.home-tool-search')){box.hidden=true;input.setAttribute('aria-expanded','false')}})}
function directory(){var input=document.getElementById('toolDirectorySearch'),status=document.getElementById('toolDirectoryStatus');if(!input)return;var cards=Array.prototype.slice.call(document.querySelectorAll('.tool-card'));function apply(q){q=String(q||'').trim();var visible=0;cards.forEach(function(c){var text=norm(c.textContent);var ok=!q||q.toLowerCase().split(/\s+/).every(function(w){return text.indexOf(w)>=0});c.style.display=ok?'':'none';if(ok)visible++});status.textContent=q?(visible+' matching tool'+(visible===1?'':'s')+' found for “'+q+'”.'):(cards.length+' tools available.');var sections=Array.prototype.slice.call(document.querySelectorAll('main section'));sections.forEach(function(sec){if(!sec.querySelector('.tool-card'))return;var any=Array.prototype.some.call(sec.querySelectorAll('.tool-card'),function(c){return c.style.display!=='none'});sec.style.display=any?'':'none'})}
var q=new URLSearchParams(location.search).get('search')||'';input.value=q;apply(q);input.addEventListener('input',function(){history.replaceState(null,'','?search='+encodeURIComponent(input.value));apply(input.value)});var clear=document.getElementById('toolDirectoryClear');if(clear)clear.addEventListener('click',function(){input.value='';history.replaceState(null,'',location.pathname);apply('');input.focus()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){home();directory()});else{home();directory()}
})();
